### ISSUE TITLE
1.10.2 wont work well

### ISSUE THREAD

**Issue by JoeSGT** [Redrield/chatcoloursplus#5] opened 2017-08-13 01:41 UTC
Hello i saw this https://github.com/Redrield/chatcoloursplus/issues/3
and used 1.2 and it keep spamming my console with this error
https://pastebin.com/1bR92W07
is there any fix ? please

**Comment by Redrield** [comment] 2017-08-13 02:42
Use the solution from that issue.

**Comment by JoeSGT** [comment] 2017-08-13 04:26
@Redrield  I did i said i used 1.2 meaning that i use **ChatColoursPlus version 1.2 and it still causing console spam** https://pastebin.com/1bR92W07

**Comment by Redrield** [comment] 2017-08-13 17:15
Could not reproduce on latest SpongeVanilla 1.10.2 build using version 1.2 of the plugin

**Comment by JoeSGT** [comment] 2017-08-13 19:47
here how to reproduce it 
1) get the latest SpongeForge not SpongeVanilla 
2) then installed ChatColoursPlus Version 1.2
2) talk in chat
3) you'll see errors in console 
each time you talk in chat send an error in console

**Comment by Redrield** [comment] 2017-08-13 20:52
Fixed in release 1.2.1

**Closed by Redrield** 2017-08-13 20:52 UTC
Labels: Status: Fixed, Type: Bug
